name: benchmarks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - gha**

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: g++-11
            compileroptions: -std=c++2a -O3 -DNDEBUG
            sourcefile: string.cpp
            outputfile: benchmark
            os: ubuntu-20.04
            install: g++-11
          - compiler: clang++
            compileroptions: -std=c++2a -O3 -DNDEBUG
            sourcefile: string.cpp
            outputfile: benchmark
            os: ubuntu-20.04

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        if: matrix.install
        run: |
          sudo -E apt-add-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt install -y ${{matrix.install}}
          
      - name: Install Boost
        run: |
          git clone https://github.com/boostorg/boost.git boost-root
          cd boost-root
          git checkout boost-1.78.0
          git submodule update --init
          ./bootstrap.sh
          ./b2 -d0 headers
          sudo cp -rp * /usr/local/include/

      - name: Compile
        run: |
          cd $GITHUB_WORKSPACE
          ${{matrix.compiler}} --version
          ${{matrix.compiler}} ${{matrix.sourcefile}} ${{matrix.compileroptions}} -o ${{matrix.outputfile}}

      - name: Run benchmarks
        run: |
          ./${{matrix.outputfile}}

  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: cl
            compileroptions: /std:c++latest /O2 /D "NDEBUG" /EHsc /MD /Fe:benchmark.exe
            sourcefile: string.cpp
            outputfile: benchmark.exe            
            os: windows-2019

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Compile
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ${{matrix.compiler}} ${{matrix.sourcefile}} ${{matrix.compileroptions}}

      - name: Run benchmark
        shell: cmd
        run: |
          ${{matrix.outputfile}}
