name: benchmarks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - gha**

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: g++-11
            compileroptions: -std=c++2a -O3 -DNDEBUG
            sourcefile: string.cpp
            outputfile: Perf
            os: ubuntu-20.04
            install: g++-11
          - compiler: clang++
            compileroptions: -std=c++2a -O3 -DNDEBUG
            sourcefile: string.cpp
            os: ubuntu-20.04

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        if: matrix.install
        run: |
          sudo -E apt-add-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt install -y ${{matrix.install}}

      - name: Compile
        run: |
          cd $GITHUB_WORKSPACE
          ${{matrix.compiler}} --version
          ${{matrix.compiler}} ${{matrix.sourcefile}} ${{matrix.compileroptions}} -o ${{matrix.outputfile}}

      - name: Run tests
        run: |
          ./${{matrix.outputfile}}

  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: cl
            compileroptions: /std:c++latest /O2 /D "NDEBUG" /EHsc /MD
            sourcefile: perf.cpp
            outputfile: perf.exe
            os: windows-2019

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Compile
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set INCLUDE=%INCLUDE%;C:\opt\github\range-v3\include
          set INCLUDE=%INCLUDE%;%GITHUB_WORKSPACE%\include
          set INCLUDE=%INCLUDE%;C:\opt\github\nanobench\src\include
          echo %INCLUDE%
          ${{matrix.compiler}} ${{matrix.sourcefile}} ${{matrix.compileroptions}}

      - name: Run tests
        shell: cmd
        run: |
          ${{matrix.outputfile}}
